<?php

use Illuminate\Database\Seeder;

class UserTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('user')->delete();

        \DB::table('user')->insert(array(

            array(
                'created_at' => 1561650441,
                'deleted_at' => null,
                //'id'         => 1,
                'is_admin'   => 1,
                'is_demo'    => 0,
                'login'      => 'system@mthash.com',
                'name'       => 'system',
                'password'   => '$2y$10$5qj.ILMl7IX1JAeRByAvGeVEJQ7a8D4V8dZFoB3oWNOfy3QoXQ/s6',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => 1563737679,
            ),

            array(
                'created_at' => 1561650442,
                'deleted_at' => null,
                //'id'         => 1,
                'is_admin'   => 1,
                'is_demo'    => 0,
                'login'      => 'eakhundzade@gmail.com',
                'name'       => 'Elkin',
                'password'   => '$2y$10$5qj.ILMl7IX1JAeRByAvGeVEJQ7a8D4V8dZFoB3oWNOfy3QoXQ/s6',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => 1563737679,
            ),

            array(
                'created_at' => 1561883838,
                'deleted_at' => null,
                //'id'         => 2,
                'is_admin'   => 1,
                'is_demo'    => 0,
                'login'      => 'admin@mthash.com',
                'name'       => 'John',
                'password'   => '$2y$10$IJCDrdtADv7pcL6YuAnGIuKbQyAAeZqLcTnlmUqJM3CAH.MyyiACS',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561915710,
                'deleted_at' => null,
                //'id'         => 3,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'john@mthash.com',
                'name'       => 'John',
                'password'   => '$2y$10$qH2spiS1Wf6OjaDWxUEJqOzlTabW6p/xOoIvkLUBULtCvtdsTem06',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561915937,
                'deleted_at' => null,
                //'id'         => 4,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'reset@mail.com',
                'name'       => 'fasdf',
                'password'   => '$2y$10$6ZXU3BuDotWPepCKmL0H2OX0MgyEweSkzNUokzl1xcWYx.7AtmXrW',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561923381,
                'deleted_at' => null,
                //'id'         => 5,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin2@mthash.com',
                'name'       => 'Test',
                'password'   => '$2y$10$WdTcAYAQXL1kw5NCa91bQOUgW242qMGwHaMPH9ar9ShUAe/2MmOoW',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561924085,
                'deleted_at' => null,
                //'id'         => 6,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin3@mthash.com',
                'name'       => 'Test2',
                'password'   => '$2y$10$go/lM4jalrtjLtACT078EOFvl/jSYimAOskSNc5YAVbSja4NBW.bK',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561924491,
                'deleted_at' => null,
                //'id'         => 7,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin4@mthash.com',
                'name'       => 'Test 4',
                'password'   => '$2y$10$iri3zqgd7UAAW1LLNNdlpORyBuywn9KZg7Ea6ei9H.5iiO4YjBp6O',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561925640,
                'deleted_at' => null,
                //'id'         => 8,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin5@mthash.com',
                'name'       => 'test 5',
                'password'   => '$2y$10$Qo6pVSBLAOqikdcdZd6tcOVimyrlJLmvllsUc0V6Iw9fuOdj/QQia',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561952972,
                'deleted_at' => null,
                //'id'         => 9,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin6@mthash.com',
                'name'       => 'Test 6',
                'password'   => '$2y$10$ugq6Iow959GHqhqlxGZhqOZooj2SSxQwgM9aYewBCkh0CBsGHNfWe',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561953096,
                'deleted_at' => null,
                //'id'         => 10,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin7@mthash.com',
                'name'       => 'Test 7',
                'password'   => '$2y$10$C0eFiGiJ7uL563wYsD/qPulbM7YN5bYYaZIb0.xaf5ewniXfUmfuW',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561953135,
                'deleted_at' => null,
                //'id'         => 11,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin8@mthash.com',
                'name'       => 'test 8',
                'password'   => '$2y$10$vEF.0i0T1jBaDj3hpB9j3eHth4JRfQMhOmBwlpDv1N.SKIBiYO996',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561953170,
                'deleted_at' => null,
                //'id'         => 12,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin9@mthash.com',
                'name'       => 'Test 9',
                'password'   => '$2y$10$lrM.zuATt3bAvjj6SdRIu.YootMQPwOCWlcxbuhYACdKfQPWOwQcW',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561955064,
                'deleted_at' => null,
                //'id'         => 13,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin10@mthash.com',
                'name'       => 'Test 10',
                'password'   => '$2y$10$rWmc6GUkAINp23eP2H7pbuht3eof1cY9tgX/tjCZYEIkmGOW/53dG',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1561955092,
                'deleted_at' => null,
                //'id'         => 14,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin11@mthash.com',
                'name'       => 'Test 11',
                'password'   => '$2y$10$SGkJrli1YusaPyxWGdpCsO11s4JHPsv0MuAM4jhWF.XpCqIiD./kK',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1562427137,
                'deleted_at' => null,
                //'id'         => 15,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'admin12@mthash.com',
                'name'       => 'fsdf',
                'password'   => '$2y$10$GkZ5qdnHC2kcbGCsi.ByfOdGuuzMVZSpRrU/4W6N3pAbSeGc1hSM6',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1562589822,
                'deleted_at' => null,
                //'id'         => 16,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'test@mthash.com',
                'name'       => 'Test',
                'password'   => '$2y$10$i3gpb.mpXxVeIj/q254/9.k9xY4JgZCiCh2rT1Nv.2myEcltbmOX.',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1562589868,
                'deleted_at' => null,
                //'id'         => 17,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'tester@mthash.com',
                'name'       => 'Tester',
                'password'   => '$2y$10$MpReSLXIpebVZxUKQ6KAn.y0zz/jv4z3d9fbytUQeFBEb7C3HOZMK',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1562589917,
                'deleted_at' => null,
                //'id'         => 18,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'ozeynaloff@gmail.com',
                'name'       => 'Orkhan Zeynaloff',
                'password'   => '$2y$10$RwiMd1NdZHwrL7ap2MHSeewcMqUEOjD5yfnqatBO2hRKi05lrEpFK',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1562589937,
                'deleted_at' => null,
                //'id'         => 19,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'o.zeynaloff@gmail.com',
                'name'       => 'Orkhan Zeynalli',
                'password'   => '$2y$10$xGaaFzlzTA0E9OXnYe.4duprRrYNGlqP8SBuUs79I1ZTlY54TXYPy',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1563788353,
                'deleted_at' => null,
                //'id'         => 20,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'zeynaloff@gmail.com',
                'name'       => 'Orkhan Zeynalli',
                'password'   => '$2y$10$yGuXfAXOkWoXSg.sv6f8Ku5heW5XM9YJpFQiNzT2kD.wlAOPNd2I6',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1563918624,
                'deleted_at' => null,
                //'id'         => 21,
                'is_admin'   => 1,
                'is_demo'    => 0,
                'login'      => 'winnalkuo@gmail.com',
                'name'       => 'Winnal Kuo',
                'password'   => '$2y$10$m.JYHn6F.BW7GgND9eYTS.b25ugqkJk1exNoEAf16Ay5Zp3QOntUW',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1565353539,
                'deleted_at' => null,
                //'id'         => 22,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo@mthash.com',
                'name'       => 'Demo User',
                'password'   => '$2y$10$351iV9htoXiVi/O7iBGjX.5cM9HFIACvNG.YmVQDdoHilA7wljzIW',
                'status'     => 1,
                'tag'        => 'origin',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1565891607,
                'deleted_at' => null,
                //'id'         => 23,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1@mthash.com',
                'name'       => 'Demo #1 User',
                'password'   => '$2y$10$MP0.DyL8yANCvbs6Uu0WjepRal28DsItHk6.GF9vbuGZb.31c1GGG',
                'status'     => 1,
                'tag'        => '1',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566026369,
                'deleted_at' => null,
                //'id'         => 24,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1566026368@mthash.com',
                'name'       => 'Demo #1566026368 User',
                'password'   => '$2y$10$8wuRP/HWJmQeVunao0Y9..GZynZKSz9KJk3kyUue63u8Qyy1jDd/i',
                'status'     => 1,
                'tag'        => '1566026368',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566149637,
                'deleted_at' => null,
                //'id'         => 26,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-090@mthash.com',
                'name'       => 'Demo 090-User',
                'password'   => '$2y$10$cHD9M3aBsf5LAXamo1724ubsj8MdIjz/t7VChm.VU.WUElUr/rYnC',
                'status'     => 1,
                'tag'        => '090',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566149682,
                'deleted_at' => null,
                //'id'         => 27,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-Test@mthash.com',
                'name'       => 'Demo Test-User',
                'password'   => '$2y$10$YKPNRHwURUqQw9txrwbNeO2YLriJ0t0MwwuRNDNwYQTzJhwYEaCeq',
                'status'     => 1,
                'tag'        => 'Test',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566151266,
                'deleted_at' => null,
                //'id'         => 28,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-{identifier}@mthash.com',
                'name'       => 'Demo {identifier}-User',
                'password'   => '$2y$10$x7ifSgT5wKRGZ3Dqqi.phe1CTgPOs6ZZ34l8Vb3rUOCkmAkLKe6k2',
                'status'     => 1,
                'tag'        => '{identifier}',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566154196,
                'deleted_at' => null,
                //'id'         => 29,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1566154190577@mthash.com',
                'name'       => 'Demo 1566154190577-User',
                'password'   => '$2y$10$BCZCSmdi/439KLNY6Yd7Euv/0.GAh7hrSDIraRIjLDF7SnI3dsCke',
                'status'     => 1,
                'tag'        => '1566154190577',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566212323,
                'deleted_at' => null,
                //'id'         => 30,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1566212297877@mthash.com',
                'name'       => 'Demo 1566212297877-User',
                'password'   => '$2y$10$wamkafhqw2Zq7Tr1ZRfkJOrSmLe3zrzJhTVeD8tO4ArVmKppZt4yq',
                'status'     => 1,
                'tag'        => '1566212297877',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566313116,
                'deleted_at' => null,
                //'id'         => 31,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-123@mthash.com',
                'name'       => 'Demo 123-User',
                'password'   => '$2y$10$0mV514q372sUeFbcV9EIMeHBrxJywK9KQS0OzjVYzkuOHhkMpvhI.',
                'status'     => 1,
                'tag'        => '123',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1566314209,
                'deleted_at' => null,
                //'id'         => 32,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1566314208@mthash.com',
                'name'       => 'Demo 1566314208-User',
                'password'   => '$2y$10$/p8UA6tSgWZxg0Hk9cW7D.0.71q9sWBKzuS.0R8ypvlENaOCTQJEm',
                'status'     => 1,
                'tag'        => '1566314208',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567010238,
                'deleted_at' => null,
                //'id'         => 33,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567010238@mthash.com',
                'name'       => 'Demo 1567010238-User',
                'password'   => '$2y$10$AVk.f/h5.hJjP4CKa1GS5OJANDP0HPyfYOp228SUnhBUhQ0OEM2E.',
                'status'     => 1,
                'tag'        => '1567010238',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567091048,
                'deleted_at' => null,
                //'id'         => 34,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567091048@mthash.com',
                'name'       => 'Demo 1567091048-User',
                'password'   => '$2y$10$vjmfpZYQ1o7e1VFedPDNHu7PQTk5h5HED1sUgdB8YPUAKy8GXQUa6',
                'status'     => 1,
                'tag'        => '1567091048',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567096988,
                'deleted_at' => null,
                //'id'         => 35,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567096988@mthash.com',
                'name'       => 'Demo 1567096988-User',
                'password'   => '$2y$10$Eiy0AUpMjULx2dK.NCjOo.0ApaliT05Xiq0drFvsrDZvJzmqs0BJq',
                'status'     => 1,
                'tag'        => '1567096988',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567116326,
                'deleted_at' => null,
                //'id'         => 36,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567116325@mthash.com',
                'name'       => 'Demo 1567116325-User',
                'password'   => '$2y$10$3ycjmEOOS.JQ1hX3vDVUNeQThxme2Nbuiyqr1kxlx9YKZJrSaotna',
                'status'     => 1,
                'tag'        => '1567116325',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567159598,
                'deleted_at' => null,
                //'id'         => 37,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567159598@mthash.com',
                'name'       => 'Demo 1567159598-User',
                'password'   => '$2y$10$ydYjFXtp/BdVcfQnbxurZuWQvgjaEKH/WvfbBUqcdh5I2UMPHacLW',
                'status'     => 1,
                'tag'        => '1567159598',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567159600,
                'deleted_at' => null,
                //'id'         => 38,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567159600@mthash.com',
                'name'       => 'Demo 1567159600-User',
                'password'   => '$2y$10$YcY2KHiPHpfanarrOBTWtOstWYaKhWG8QT7eppH3/i3IUBQ85z6Ta',
                'status'     => 1,
                'tag'        => '1567159600',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567180392,
                'deleted_at' => null,
                //'id'         => 39,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567180392@mthash.com',
                'name'       => 'Demo 1567180392-User',
                'password'   => '$2y$10$i48oaj2NK666CZdq1EElZeZFs6YsKyvaPA6eM1fEQQMb2Xk9Jnu4S',
                'status'     => 1,
                'tag'        => '1567180392',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567557037,
                'deleted_at' => null,
                //'id'         => 40,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567557037@mthash.com',
                'name'       => 'Demo 1567557037-User',
                'password'   => '$2y$10$YBwWjTdcTBJgweWLM2ooZ.AE/CCJjJye7mPovNJIbhqOm5S9O8PF.',
                'status'     => 1,
                'tag'        => '1567557037',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567557041,
                'deleted_at' => null,
                //'id'         => 41,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567557041@mthash.com',
                'name'       => 'Demo 1567557041-User',
                'password'   => '$2y$10$r6JyBb5jmLcluxU.RMibTe8ftftg2Hx9.Obz4h/a92w84sJeACpmu',
                'status'     => 1,
                'tag'        => '1567557041',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1567557042,
                'deleted_at' => null,
                //'id'         => 42,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1567557042@mthash.com',
                'name'       => 'Demo 1567557042-User',
                'password'   => '$2y$10$jFo5v.imb16IkWVCwzB53u4Mc.acatOTaWTL6SeZUCQeMO4P3GM5a',
                'status'     => 1,
                'tag'        => '1567557042',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1568824692,
                'deleted_at' => null,
                //'id'         => 43,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1568824688606@mthash.com',
                'name'       => 'Demo 1568824688606-User',
                'password'   => '$2y$10$/yM20RRFvy37lQAKaBQkOueoWvUpq8HuONNHzkBW8qOPsXwwhu8iW',
                'status'     => 1,
                'tag'        => '1568824688606',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1569566729,
                'deleted_at' => null,
                //'id'         => 44,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1569566729@mthash.com',
                'name'       => 'Demo 1569566729-User',
                'password'   => '$2y$10$9UWNYt4PXIdTB4rEV.av/ew9TYvDKfRRmKejhkBVYGQsyD0dDt2Vi',
                'status'     => 1,
                'tag'        => '1569566729',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1569841147,
                'deleted_at' => null,
                //'id'         => 45,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'pledcoin@gmail.com',
                'name'       => 'ldpld',
                'password'   => '$2y$10$7zvb7WWGmcv.2aK696RXoejk0UMP1mUKTtMcU5VAkOhqZiJUcyesy',
                'status'     => 1,
                'tag'        => null,
                'updated_at' => null,
            ),

            array(
                'created_at' => 1570111813,
                'deleted_at' => null,
                //'id'         => 46,
                'is_admin'   => 0,
                'is_demo'    => 1,
                'login'      => 'demo-1570111813@mthash.com',
                'name'       => 'Demo 1570111813-User',
                'password'   => '$2y$10$L3D5fJr/Xb7nU4pkNHgksO57lYvWbF57f7zPzzaQ8ePg6m6TanfQe',
                'status'     => 1,
                'tag'        => '1570111813',
                'updated_at' => null,
            ),

            array(
                'created_at' => 1570116070,
                'deleted_at' => null,
                //'id'         => 47,
                'is_admin'   => 0,
                'is_demo'    => 0,
                'login'      => 'pled@email.com',
                'name'       => 'pled',
                'password'   => '$2y$10$.t2fy1Q.2M6B7aN4cgYlpOFX7tMJqbKPLD0YhlwJDiaGxMQUgGLK2',
                'status'     => 1,
                'tag'        => 'admin',
                'updated_at' => null,
            ),
        ));


    }
}
